### ISSUE TITLE
License Activation Issue

### ISSUE THREAD

**Issue by jordanrabidou** [alvarotrigo/multiscroll.js#135]
I've purchased, activated, and included activation keys for all of the multi scroll extensions however I'm still receiving the license notice.
waverlypensacola.com

**Comment by thebananaland** [comment]
I had to temporarily hide the alert as we are live. I hope you understand. Hope we can get this resolved quickly, and that it wasn't something silly on my end

**Comment by alvarotrigo** [comment]
No worries! And apologies for the inconvenience! 
We've fixed the issue and reset your activation keys counter. 

Please generate the activation keys again and you should be fine :)

**Comment by jordanrabidou** [comment]
Still Having same issue



Best,
Jordan Rabidou
------------------------
The Bananaland
www.thebananaland.com
162 Elm St.
Bridgeport CT. 06604
(203) 244-8345

**Comment by alvarotrigo** [comment]
Make sure to refresh a couple of times the activation page soo you don't get the old cached version:
https://alvarotrigo.com/fullPage/extensions/activationKey.html

**Comment by jordanrabidou** [comment]
Hi Alvaro,

Still having the same issue after reactivating keys

I also opened the activation link in a incognito browser to make sure there wasn’t a caching issue


Best,
Jordan Rabidou
------------------------
The Bananaland
www.thebananaland.com
162 Elm St.
Bridgeport CT. 06604
(203) 244-8345

**Comment by alvarotrigo** [comment]
Alright. Fixed now :)
Give it another try.

**Comment by jordanrabidou** [comment]
AHHH Thank god!

Thanks for your prompt help!

Best,
Jordan Rabidou
------------------------
The Bananaland
www.thebananaland.com
162 Elm St.
Bridgeport CT. 06604
(203) 244-8345
